spring:
  application:
    name: onlineshop
  main:
    allow-bean-definition-overriding: true # 允许覆盖相同类型的bean定义
  component-scan:
    base-packages: 
      - tokyo.kaisei

# mybatis简单配置
mybatis:
  mapper-locations: classpath:/tokyo/kaisei/dao/after/*.xml # 指定mapper映射文件
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰式映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 


